"""Add catalog tables: device_types, brands, models, dcim_connections

Revision ID: 2785cd8e7011
Revises: 
Create Date: 2026-01-11 14:26:16.702132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2785cd8e7011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='fetchconfidence'), nullable=True),
    sa.Column('fetch_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('dcim_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('NETBOX', 'RACKTABLES', 'RALPH', name='dcimtype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_token', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcim_connections_id'), 'dcim_connections', ['id'], unique=False)
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_types_id'), 'device_types', ['id'], unique=False)
    op.create_index(op.f('ix_device_types_name'), 'device_types', ['name'], unique=True)
    op.create_index(op.f('ix_device_types_slug'), 'device_types', ['slug'], unique=True)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('total_height_u', sa.Integer(), nullable=True),
    sa.Column('width_inches', sa.Enum('ELEVEN_INCH', 'EIGHTEEN_INCH', 'NINETEEN_INCH', 'TWENTY_THREE_INCH', name='widthtype'), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('max_power_watts', sa.Float(), nullable=True),
    sa.Column('cooling_type', sa.String(), nullable=True),
    sa.Column('cooling_capacity_btu', sa.Float(), nullable=True),
    sa.Column('ambient_temp_c', sa.Float(), nullable=True),
    sa.Column('max_inlet_temp_c', sa.Float(), nullable=True),
    sa.Column('airflow_cfm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('end_of_life', sa.Date(), nullable=True),
    sa.Column('height_u', sa.Float(), nullable=False),
    sa.Column('width_type', sa.String(length=10), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('power_watts', sa.Float(), nullable=True),
    sa.Column('heat_output_btu', sa.Float(), nullable=True),
    sa.Column('airflow_pattern', sa.String(length=50), nullable=True),
    sa.Column('max_operating_temp_c', sa.Float(), nullable=True),
    sa.Column('typical_ports', sa.JSON(), nullable=True),
    sa.Column('mounting_type', sa.String(length=100), nullable=True),
    sa.Column('datasheet_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_brand_id'), 'models', ['brand_id'], unique=False)
    op.create_index('ix_models_brand_name_variant', 'models', ['brand_id', 'name', 'variant'], unique=True)
    op.create_index(op.f('ix_models_device_type_id'), 'models', ['device_type_id'], unique=False)
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_table('device_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('height_u', sa.Float(), nullable=False),
    sa.Column('width_type', sa.Enum('ELEVEN_INCH', 'EIGHTEEN_INCH', 'NINETEEN_INCH', 'TWENTY_THREE_INCH', name='widthtype'), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('power_watts', sa.Float(), nullable=True),
    sa.Column('heat_output_btu', sa.Float(), nullable=True),
    sa.Column('airflow_pattern', sa.Enum('FRONT_TO_BACK', 'BACK_TO_FRONT', 'SIDE_TO_SIDE', 'PASSIVE', name='airflowpattern'), nullable=True),
    sa.Column('max_operating_temp_c', sa.Float(), nullable=True),
    sa.Column('typical_ports', sa.JSON(), nullable=True),
    sa.Column('mounting_type', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('WEB_FETCHED', 'MANUFACTURER_SPEC', 'COMMUNITY', 'USER_CUSTOM', name='sourcetype'), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('migrated_to_model_id', sa.Integer(), nullable=True),
    sa.Column('migration_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='migrationstatus'), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['migrated_to_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_specifications_brand'), 'device_specifications', ['brand'], unique=False)
    op.create_index(op.f('ix_device_specifications_id'), 'device_specifications', ['id'], unique=False)
    op.create_index(op.f('ix_device_specifications_model'), 'device_specifications', ['model'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('access_frequency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='accessfrequency'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['device_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_brand'), 'devices', ['brand'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_model'), 'devices', ['model'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_device_id', sa.Integer(), nullable=False),
    sa.Column('to_device_id', sa.Integer(), nullable=False),
    sa.Column('from_port', sa.String(), nullable=True),
    sa.Column('to_port', sa.String(), nullable=True),
    sa.Column('cable_type', sa.Enum('CAT5E', 'CAT6', 'CAT6A', 'CAT7', 'FIBER_SM', 'FIBER_MM', 'POWER', 'CONSOLE', name='cabletype'), nullable=True),
    sa.Column('cable_category_required', sa.String(), nullable=True),
    sa.Column('calculated_length_m', sa.Float(), nullable=True),
    sa.Column('routing_path', sa.Enum('DIRECT', 'CABLE_TRAY', 'CONDUIT', name='routingpath'), nullable=True),
    sa.ForeignKeyConstraint(['from_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['to_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_table('rack_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('start_u', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_positions_id'), 'rack_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rack_positions_id'), table_name='rack_positions')
    op.drop_table('rack_positions')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_devices_model'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_brand'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_specifications_model'), table_name='device_specifications')
    op.drop_index(op.f('ix_device_specifications_id'), table_name='device_specifications')
    op.drop_index(op.f('ix_device_specifications_brand'), table_name='device_specifications')
    op.drop_table('device_specifications')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_index(op.f('ix_models_device_type_id'), table_name='models')
    op.drop_index('ix_models_brand_name_variant', table_name='models')
    op.drop_index(op.f('ix_models_brand_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_device_types_slug'), table_name='device_types')
    op.drop_index(op.f('ix_device_types_name'), table_name='device_types')
    op.drop_index(op.f('ix_device_types_id'), table_name='device_types')
    op.drop_table('device_types')
    op.drop_index(op.f('ix_dcim_connections_id'), table_name='dcim_connections')
    op.drop_table('dcim_connections')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
